### PR TITLE
Enhancement: Run coding-standards job on GitHub Actions

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] runs ` coding-standards` job on GitHub Actions
* [x] runs `vendor/bin/phpcbf`

💁‍♂️ Using `squizlabs/php_codesniffer` because it is compatible and works on PHP 5.4.

### CODE REVIEW

**Comment by shrikeh** [comment]
Do we want to drop Scrutinizer?

**Comment by localheinz** [comment]
@shrikeh 

Yes, let's get rid of it!

See #9!

**Comment by localheinz** [comment]
@shrikeh 

I'll continue later - although there is not much to set up or change!

**Comment by shrikeh** [comment]
👍

**Pull request merged**
